name: Test Build and deploy to Azure

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  AZURE_REGISTRY_SERVER: "mmstiverghostacr.azurecr.io"
  NODE_VERSION: '16.14.2'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build and push
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_REGISTRY_SERVER }} 
          username: ${{ secrets.AZURE_REGISTRY_SERVER_LOGIN }}
          password: ${{ secrets.AZURE_REGISTRY_SERVER_PASSWORD }}
          
      - run: |
          docker build . -t ${{ env.AZURE_REGISTRY_SERVER }}/ghost -t ${{ env.AZURE_REGISTRY_SERVER }}/ghost:${{ github.sha }}
          docker push ${{ env.AZURE_REGISTRY_SERVER }}/ghost:${{ github.sha }}
          docker push ${{ env.AZURE_REGISTRY_SERVER }}/ghost
          
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build
        shell: pwsh
        run: |
          .\build.ps1 ${{ secrets.AZURE_ADMIN_USER }} ${{ secrets.AZURE_ADMIN_PASSWORD }}
